version: "3"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      NEO4J_AUTH: none
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  sink:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: sink
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      neo4j_uri: neo4j://neo4j:7687
      neo4j_user: neo4j
      neo4j_pass: neo4j
      SUBSTREAMS_API_TOKEN: ${SUBSTREAMS_API_TOKEN}
      SUBSTREAMS_ENDPOINT_URL: ${SUBSTREAMS_ENDPOINT_URL}
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: api
    ports:
      - "80:8080"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      neo4j_uri: neo4j://neo4j:7687
      neo4j_user: neo4j
      neo4j_pass: neo4j
