[package]
name = "kg-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
neo4rs = "0.8.0"
prost = "0.13.3"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
tracing = "0.1.40"
